
export let FORM_SESION = {
    titulo: 'Sesion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Sesion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label_i18n: 'descripcion',
        placeholder_i18n: 'descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaCreacion',
        label_i18n: 'fecha_creacion',
        placeholder_i18n: 'fecha_creacion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaModificacion',
        label_i18n: 'fecha_modificacion',
        placeholder_i18n: 'fecha_modificacion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaInicio',
        label_i18n: 'fecha_inicio',
        placeholder_i18n: 'fecha_inicio',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaFin',
        label_i18n: 'fecha_fin',
        placeholder_i18n: 'fecha_fin',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Periodo',
        label_i18n: 'periodo',
        placeholder_i18n: 'periodo',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Recurrente',
        label_i18n: 'recurrente',
        placeholder_i18n: 'recurrente',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'NumeroRecurrencias',
        label_i18n: 'numero_recurrencias',
        placeholder_i18n: 'numero_recurrencias',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoSesion',
        label_i18n: 'tipo_sesion',
        placeholder_i18n: 'tipo_sesion',
        requerido: true,
        tipo: 'TipoSesion',
        // key: 'Name',
        opciones: [],
    },
    ],
}
