
export let FORM_SESION = {
    titulo: 'Sesion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'Sesion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label: 'Id*:',
        placeholder: 'Ej. Id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Descripcion',
        label: 'Descripcion*:',
        placeholder: 'Ej. Descripcion',
        requerido: true,
        tipo: 'text',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaCreacion',
        label: 'FechaCreacion*:',
        placeholder: 'Ej. FechaCreacion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaModificacion',
        label: 'FechaModificacion*:',
        placeholder: 'Ej. FechaModificacion',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaInicio',
        label: 'FechaInicio*:',
        placeholder: 'Ej. FechaInicio',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'mat-date',
        claseGrid: 'col-6',
        nombre: 'FechaFin',
        label: 'FechaFin*:',
        placeholder: 'Ej. FechaFin',
        requerido: true,
        tipo: 'date',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Periodo',
        label: 'Periodo*:',
        placeholder: 'Ej. Periodo',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'checkbox',
        claseGrid: 'col-6',
        nombre: 'Recurrente',
        label: 'Recurrente*:',
        placeholder: 'Ej. Recurrente',
        requerido: true,
        tipo: 'checkbox',
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'NumeroRecurrencias',
        label: 'NumeroRecurrencias*:',
        placeholder: 'Ej. NumeroRecurrencias',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'TipoSesion',
        label: 'TipoSesion*:',
        placeholder: 'Ej. TipoSesion',
        requerido: true,
        tipo: 'TipoSesion',
        // key: 'Name',
        opciones: [],
    },
    ],
}
