
export let FORM_PARTICIPANTE_SESION = {
    titulo: 'ParticipanteSesion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'ParticipanteSesion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Sesion',
        label_i18n: 'sesion',
        placeholder_i18n: 'sesion',
        requerido: true,
        tipo: 'Sesion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'RolParticipanteSesion',
        label_i18n: 'rol_participante_sesion',
        placeholder_i18n: 'rol_participante_sesion',
        requerido: true,
        tipo: 'RolParticipanteSesion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Ente',
        label_i18n: 'ente',
        placeholder_i18n: 'ente',
        requerido: true,
        tipo: 'number',
    },
    ],
}
