
export let FORM_PARTICIPANTE_SESION = {
    titulo: 'ParticipanteSesion',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'ParticipanteSesion',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label: 'Id*:',
        placeholder: 'Ej. Id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'Sesion',
        label: 'Sesion*:',
        placeholder: 'Ej. Sesion',
        requerido: true,
        tipo: 'Sesion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'RolParticipanteSesion',
        label: 'RolParticipanteSesion*:',
        placeholder: 'Ej. RolParticipanteSesion',
        requerido: true,
        tipo: 'RolParticipanteSesion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Ente',
        label: 'Ente*:',
        placeholder: 'Ej. Ente',
        requerido: true,
        tipo: 'number',
    },
    ],
}
