
export let FORM_RELACION_SESIONES = {
    titulo: 'RelacionSesiones',
    tipo_formulario: 'mini',
    btn: 'Guardar',
    alertas: true,
    modelo: 'RelacionSesiones',
    campos: [
    {
        etiqueta: 'input',
        claseGrid: 'col-6',
        nombre: 'Id',
        label_i18n: 'id',
        placeholder_i18n: 'id',
        requerido: true,
        tipo: 'number',
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'SesionPadre',
        label_i18n: 'sesion_padre',
        placeholder_i18n: 'sesion_padre',
        requerido: true,
        tipo: 'Sesion',
        // key: 'Name',
        opciones: [],
    },
    {
        etiqueta: 'select',
        claseGrid: 'col-6',
        nombre: 'SesionHijo',
        label_i18n: 'sesion_hijo',
        placeholder_i18n: 'sesion_hijo',
        requerido: true,
        tipo: 'Sesion',
        // key: 'Name',
        opciones: [],
    },
    ],
}
